services:
  db:
    image: postgres:16
    container_name: pcc_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pcc
      POSTGRES_USER: pcc
      POSTGRES_PASSWORD: pcc_password
    volumes:
      - pcc_db_data:/var/lib/postgresql/data

volumes:
  pcc_db_data:
